### ISSUE TITLE
Integration to ccxt

### ISSUE THREAD

**Issue by jothi-devhub** [SaxoBank/openapi-samples-csharp#77]
I am trying integrate Saxo Open API to FreqTrade.As part of this I need to add the api to CCXT library need help Please review here forked_ccxt and provide your suggestions.

[Forked_ccxt](https://github.com/jothi-devhub/ccxt)

**Comment by gidven** [comment]
Hi there, unfortunately this is not something we can assist with. You can however use the samples provided in our github repos to get an understanding of what an integration might look like.
