### ISSUE TITLE
Please delete, wrong repo

### ISSUE THREAD

**Issue by wislon** [SaxoBank/openapi-samples-csharp#8]
Need to log in first, get access token and refresh token

* See https://www.developer.saxo/openapi/learn for starting
* See https://github.com/SaxoBank/openapi-samples-csharp for example of how to implement PKCE auth flow (needed coz we're not using a web application, but doing this from console/cloud functions

- [ ] Request a simulation account so we have a playground.
- [ ] Build basic console app based on sample
- [ ] Store Access and Refresh Tokens (file based only for now)
- [ ] Confirm we can get a new Refresh Token based on an existing (expired?) one

**Comment by basgroot** [comment]
Hi Wislon,

We already have a PKCE console app for C#.
Can you take a look here: https://github.com/SaxoBank/openapi-samples-csharp/tree/master/authentication/Authentication_PKCE

Or is it something else you'd like to add?

Regards,
Bas

**Comment by wislon** [comment]
Hey @basgroot I'm sorry about that, I was distracted and created this issue in the wrong repo. This is really embarrassing! 😊  
I'm going to close it.

Nice to know you're paying attention and responding that quickly tho! 👍🏻
